spring:
  datasource:
    url: jdbc:mysql://0.0.0.0/test?useSSL=false
    username: root
    password: ''
  flyway:
    baseline-on-migrate: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    lazy-load-trigger-methods: true
logging.level.com.example.kotlin.infrastructure:
  GroupMapperRepository: DEBUG
  MemberMapperRepository: DEBUG
