spring:
  datasource:
    url: jdbc:mysql://0.0.0.0/test?useSSL=false
    username: root
    password: ''
  flyway:
    baseline-on-migrate: true
mybatis:
  type-aliases-package: com.example.java.model
  configuration:
    map-underscore-to-camel-case: true
logging.level.com.example.java.infrastructure:
  GroupMapperRepository: DEBUG
  MemberMapperRepository: DEBUG
